### ISSUE TITLE
Can we limit logs from only certain containers

### ISSUE THREAD

**Issue by KrishnaPravin** [andrea-falco/lens-multi-pod-logs#10]
Currently logs from all the containers in all the pods are being written to the terminal. Could we have an option to select only specific containers. I think having sub menus to select a container would be possible in lens.

**Comment by andrea-falco** [comment]
Hi @mapelpapel, the 3 sub-menus are shown only if the Pods of the Deployment _(or StatefulSets/ReplicaSets/DaemonSets)_ have **at least 2 containers**.
