### ISSUE TITLE
lens-multi-pod-logs not showing on the menu

### ISSUE THREAD

**Issue by RocketDevRepo** [andrea-falco/lens-multi-pod-logs#14]
Hello

On Windows lens-multi-pod-logs are not showing on the menu. See below screenshot.

![lensmenu](https://github.com/andrea-falco/lens-multi-pod-logs/assets/151520581/750ca220-bc51-44e5-9ead-817dc6083dbe)

lensversion

![lensversion](https://github.com/andrea-falco/lens-multi-pod-logs/assets/151520581/400ff1a7-8adc-4759-897b-186da1ae1c40)

Sternversion

C:\>stern -v
version: 1.30.0
commit: 72e2de21fdcae1af295dc8b10bba41398aa590af
built at: 2024-05-24T00:03:22Z

The extension is enabled

![exlens](https://github.com/andrea-falco/lens-multi-pod-logs/assets/151520581/467e750a-e567-4394-9a44-b364df93ccab)

Happy to assist with additional info you might need

**Comment by andrea-falco** [comment]
Hi @RocketDevRepo, I have some questions:
- In which resource are you trying to use the menu?
- Is the resource type one of those supported? So Deployments, StatefulSets, ReplicaSets or DaemonSets?
- Does the resource have at least 1 active replica?

**Comment by andrea-falco** [comment]
Hi @RocketDevRepo, you solved the problem?
If yes, I'll close the issue.
