### ISSUE TITLE
Starting multi-pod logs shows error

### ISSUE THREAD

**Issue by joniba** [andrea-falco/lens-multi-pod-logs#15]
First of all, thanks for the great extension. It's been working great for months. But today for some reason it stopped working. Not sure what changed. Running multi-pod logs now opens two terminals, both with the same errors:

```
C:\Users\jbenami\AppData\Roaming\OpenLens\binaries\kubectl\1.27.3 : The term
'C:\Users\jbenami\AppData\Roaming\OpenLens\binaries\kubectl\1.27.3' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:14
+ ...  {$Env:PATH=C:\Users\jbenami\AppData\Roaming\OpenLens\binaries\kubect ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\jbenam...\kubectl\1.27.3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

C:\Users\jbenami\AppData\Roaming\OpenLens\binaries : The term 'C:\Users\jbenami\AppData\Roaming\OpenLens\binaries' is
not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At line:1 char:80
+ ... ectl\1.27.3;C:\Users\jbenami\AppData\Roaming\OpenLens\binaries;$Env:P ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\jbenam...enLens\binaries:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

The path `C:\Users\jbenami\AppData\Roaming\OpenLens\binaries\kubectl\1.27.3` exists and contains kubectl.exe.
Single pod logs still work. 
Kubectl works on any other terminal normally.
Stern works on any other terminal. 

Running latest OpenLens (6.5.2), latest extension (0.3.7), windows 11 enterprise.

**Comment by andrea-falco** [comment]
Hi @joniba, have you installed stern using krew?
If yes, take a look here: #3

**Comment by joniba** [comment]
Hi @andrea-falco, no, I installed stern via _choco_. All stern commands are working as expected from a standard terminal. I even wrote a script to tail logs from all of my pods into the same terminal in the meantime until (hopefully) this extension is working again.

Another update, my co-worker opened OpenLens today and got the same behavior. Not sure what changed or where to cause this, but it seems to have been in the past few days.

**Comment by andrea-falco** [comment]
Hi @joniba, do you have any news?

**Comment by joniba** [comment]
hi @andrea-falco, this error resolved itself. Very strange. I made no changes to the extension or openlens or my windows environment, but it just started working again.

Thanks for your help!
