### ISSUE TITLE
Not compatible with openlens-node-pod-menu

### ISSUE THREAD

**Issue by syepes** [andrea-falco/lens-multi-pod-logs#4]
When both openlens-node-pod-menu + lens-multi-pod-logs are installed none of them work :-(

It would be great if we could have both extensions installed at the same time.

**Comment by andrea-falco** [comment]
Hi Sebastian,
if you're using the 6.5.2 version of OpenLens, there is an issue that disable all the extension at the startup.

You need to update to the latest versione to resolve.
If instead you will still have the problem, please re-open the issue with more details.

Thanks,
Andrea
