### ISSUE TITLE
Error: stern reached the maximum number of log requests (50)

### ISSUE THREAD

**Issue by HattabbI4** [andrea-falco/lens-multi-pod-logs#7]
Hi! 
I have deployment with 30 pods and 3 containers. 

When i try to read logs i get this error:
```
stern deployment/api --color auto --namespace default --since 1s
➜  ~ stern deployment/api --color auto --namespacedefault --since 1s
...
CUT: <list of pods and container>
...
Error: stern reached the maximum number of log requests (50), use --max-log-requests to increase the limit 
```

how can i pass this parameter?

**Comment by andrea-falco** [comment]
Hi @HattabbI4, I have just released a new version (v0.3.4) which includes a new preference to set the `--max-log-requests` parameter.

You can see below a screeenshot of the new preference:

![preferences](https://github.com/andrea-falco/lens-multi-pod-logs/assets/23004377/c53fa5f3-ed5c-446d-bf35-a5e93ebad9af)
