### ISSUE TITLE
Option to add custom template

### ISSUE THREAD

**Issue by mapelpapel** [andrea-falco/lens-multi-pod-logs#8]
I am using a custom template for stern to not have such a long prefix as the default.
Right now, I have to execute the command manually.

Could you add an option to be able to add a custom template in the settings?
I guess a simple text box which's content (if not empty) gets appended to the command with the --template -Tag would be enough.

**Comment by andrea-falco** [comment]
Hi @mapelpapel,
I'm planning to add this feature during the next weekend.

**Comment by andrea-falco** [comment]
Hi @mapelpapel, I have just released a new version (v0.3.5) which includes 2 new preferences for built-in and custom template.
The second one will set the `--template` flag on stern command.

You can see below a screenshot of the new preferences:

![template-preferences](https://github.com/andrea-falco/lens-multi-pod-logs/assets/23004377/5ca5b79a-da44-4f21-ba18-377e45005711)
