### ISSUE TITLE
Find / copy support?

### ISSUE THREAD

**Issue by jdolan-chwy** [andrea-falco/lens-multi-pod-logs#9]
Hi, will these features be added at some point? Or am I missing something obvious to enable them?

**Comment by andrea-falco** [comment]
Hi, could you explain better what you mean?

**Comment by jdolan-chwy** [comment]
Hi, thanks for the response.

When I view the logs for a deployment in OpenLens, I can _select_ some text from the log, but I can't copy it to the clipboard for whatever reason. The proprietary Lens log viewer (while not multi-pod) lets you select and copy, which is quite handy when I'm trying to send a backtrace to a coworker or capture it on a Jira ticket or whatever.

That's a bummer that OpenLens doesn't let you open a little Cmd+F modal inside the log viewer, but I agree that searching for something specific probably warrants dropping to the command line anyway.

**Comment by andrea-falco** [comment]
Hi @jdolan-chwy,
for select and copy I don't understand what you mean, I can select and copy text (with Ctrl+C or Cmd+C) on terminal.

Maybe depend on which terminal you are using, check your Lens/OpenLens preferences.

**Comment by jdolan-chwy** [comment]
Weird! I had to check, and then uncheck, the setting for "Copy on select and paste on right click" and now I can copy from the logs with Cmd-C as you'd expect. So strange!

Fwiw, I'm using OpenLens 6.5.2 on macOS with the zsh shell, and the default terminal emulation in Lens. 🤷‍♂️ 

I'll go ahead and close this bug. Thank you for your replies!
